version: "3"
services:
  server:
    image: <image_du_serveur>
    ports:
      - 4000:4000
    volumes:
      - <chemin_vers_code_du_serveur>:/app
    command: <commande_de_demarrage_du_serveur>

  client:
    image: <image_du_client>
    ports:
      - 3000:3000
    volumes:
      - <chemin_vers_code_du_client>:/app
    command: npm run start
