version: "0.1"
services:
  server:
    build: ./server
    ports:
      - 4000:4000
    volumes:
      - ./server/app:/servcer/app
    command: npm run dev

  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/app:/client/app
    command: npm run dev
